# JobRegistry Development Commands
# Usage: just <command>

# Load environment variables from .env.local
set dotenv-load
set dotenv-filename := ".env.local"

# Default anvil test account (first pre-funded account with 10,000 ETH)
export LOCAL_ETH_PRIVATE_KEY1 := "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
export RPC_URL := "http://127.0.0.1:8545"

# Start Anvil and deploy all contracts (local dev environment)
eth-dev:
    #!/usr/bin/env bash
    set -e
    cd contracts

    echo "Building contracts..."
    forge build

    echo "Starting Anvil in background..."
    anvil &
    ANVIL_PID=$!

    # Wait for Anvil to be ready
    sleep 2

    echo "Deploying contracts..."
    forge script script/DeployJobRegistry.s.sol \
        --rpc-url {{RPC_URL}} \
        --private-key {{LOCAL_ETH_PRIVATE_KEY1}} \
        --broadcast

    # Extract deployed address and update frontend config
    REGISTRY_ADDRESS=$(cat broadcast/DeployJobRegistry.s.sol/31337/run-latest.json | jq -r '.transactions[1].contractAddress')
    BLOCK_NUMBER=$(cat broadcast/DeployJobRegistry.s.sol/31337/run-latest.json | jq -r '.receipts[1].blockNumber' | xargs printf "%d")

    OUTPUT_FILE="../apps/web/src/lib/contracts.generated.ts"
    echo "// Auto-generated by: just eth-dev" > "$OUTPUT_FILE"
    echo "// Do not edit manually - re-run deployment to update" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "export const JOB_REGISTRY_ADDRESS = \"${REGISTRY_ADDRESS}\" as \`0x\${string}\`;" >> "$OUTPUT_FILE"
    echo "export const DEPLOYMENT_BLOCK = BigInt(${BLOCK_NUMBER});" >> "$OUTPUT_FILE"
    echo "export const CHAIN_ID = 31337;" >> "$OUTPUT_FILE"

    # Generate wagmi TypeScript bindings
    echo "Generating wagmi bindings..."
    cd ../apps/web && pnpm generate

    echo ""
    echo "============================================"
    echo "Local dev environment ready!"
    echo "Anvil PID: $ANVIL_PID"
    echo "RPC URL: {{RPC_URL}}"
    echo "JobRegistry: $REGISTRY_ADDRESS"
    echo "============================================"
    echo ""
    echo "Press Ctrl+C to stop Anvil"

    # Keep script running, forward signals to Anvil
    trap "kill $ANVIL_PID 2>/dev/null" EXIT
    wait $ANVIL_PID

# Build contracts
eth-build:
    cd contracts && forge build

# Run contract tests
eth-test:
    cd contracts && forge test -vvv

# Deploy to local Anvil (assumes Anvil is already running)
eth-deploy-local:
    #!/usr/bin/env bash
    set -e
    cd contracts
    forge script script/DeployJobRegistry.s.sol \
        --rpc-url {{RPC_URL}} \
        --private-key {{LOCAL_ETH_PRIVATE_KEY1}} \
        --broadcast

    # Extract deployed address from broadcast artifacts
    REGISTRY_ADDRESS=$(cat broadcast/DeployJobRegistry.s.sol/31337/run-latest.json | jq -r '.transactions[0].contractAddress')
    BLOCK_NUMBER=$(cat broadcast/DeployJobRegistry.s.sol/31337/run-latest.json | jq -r '.receipts[0].blockNumber' | xargs printf "%d")

    # Generate TypeScript config using echo (avoids just parsing issues with heredocs)
    OUTPUT_FILE="../apps/web/src/lib/contracts.generated.ts"
    echo "// Auto-generated by: just eth-deploy-local" > "$OUTPUT_FILE"
    echo "// Do not edit manually - re-run deployment to update" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "export const JOB_REGISTRY_ADDRESS = \"${REGISTRY_ADDRESS}\" as \`0x\${string}\`;" >> "$OUTPUT_FILE"
    echo "export const DEPLOYMENT_BLOCK = BigInt(${BLOCK_NUMBER});" >> "$OUTPUT_FILE"
    echo "export const CHAIN_ID = 31337;" >> "$OUTPUT_FILE"

    echo "Generated contracts.generated.ts with:"
    echo "  JOB_REGISTRY_ADDRESS: $REGISTRY_ADDRESS"
    echo "  DEPLOYMENT_BLOCK: $BLOCK_NUMBER"
    echo "  CHAIN_ID: 31337"

# Deploy to Sepolia (requires SEPOLIA_RPC_URL and DEPLOYER_KEY env vars)
eth-deploy-sepolia:
    #!/usr/bin/env bash
    set -e
    cd contracts
    forge script script/DeployJobRegistry.s.sol \
        --rpc-url $SEPOLIA_RPC_URL \
        --private-key $DEPLOYER_KEY \
        --broadcast

    # Extract deployed address from broadcast artifacts
    REGISTRY_ADDRESS=$(cat broadcast/DeployJobRegistry.s.sol/11155111/run-latest.json | jq -r '.transactions[0].contractAddress')
    BLOCK_NUMBER=$(cat broadcast/DeployJobRegistry.s.sol/11155111/run-latest.json | jq -r '.receipts[0].blockNumber' | xargs printf "%d")

    # Generate TypeScript config using echo (avoids just parsing issues with heredocs)
    OUTPUT_FILE="../apps/web/src/lib/contracts.generated.ts"
    echo "// Auto-generated by: just eth-deploy-sepolia" > "$OUTPUT_FILE"
    echo "// Do not edit manually - re-run deployment to update" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "export const JOB_REGISTRY_ADDRESS = \"${REGISTRY_ADDRESS}\" as \`0x\${string}\`;" >> "$OUTPUT_FILE"
    echo "export const DEPLOYMENT_BLOCK = BigInt(${BLOCK_NUMBER});" >> "$OUTPUT_FILE"
    echo "export const CHAIN_ID = 11155111;" >> "$OUTPUT_FILE"

    echo "Generated contracts.generated.ts with:"
    echo "  JOB_REGISTRY_ADDRESS: $REGISTRY_ADDRESS"
    echo "  DEPLOYMENT_BLOCK: $BLOCK_NUMBER"
    echo "  CHAIN_ID: 11155111 (Sepolia)"

# Fund a wallet with ETH from Anvil's test account (local only)
eth-fund address amount="100ether":
    cast send {{address}} --value {{amount}} --private-key {{LOCAL_ETH_PRIVATE_KEY1}} --rpc-url {{RPC_URL}}

# Stop any running Anvil process
eth-stop:
    #!/usr/bin/env bash
    if pgrep -x "anvil" > /dev/null; then
        echo "Stopping Anvil..."
        pkill -x "anvil"
        echo "Anvil stopped"
    else
        echo "No Anvil process running"
    fi

# Clean build artifacts
eth-clean:
    cd contracts && forge clean

# Format Solidity files
eth-fmt:
    cd contracts && forge fmt

# Start frontend dev server (Next.js)
watch-frontend-dev:
    cd apps/web && pnpm dev

# Generate wagmi TypeScript bindings from Solidity contracts
generate-bindings:
    cd apps/web && pnpm generate

# Build contracts and regenerate TypeScript bindings
eth-build-all: eth-build generate-bindings
